language: java
script:
  - SPRING_BOOT_VERSION=1.5.21.RELEASE ./mvnw clean test -B
  - SPRING_BOOT_VERSION=2.0.9.RELEASE ./mvnw clean test -B
  - SPRING_BOOT_VERSION=2.1.6.RELEASE ./mvnw clean test -B
